App\Domain\Category\Category:
  type: entity
  table: category
  uniqueConstraints:
    search_idx:
      columns: [ name ]
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      nullable: false
      length: 45
      options:
        fixed: false
    createdAt:
      type: datetime
      nullable: false
      options:
        fixed: false
lifecycleCallbacks: {  }